7.5. Фоновые задачи
htmlacademy-php3/240581-what-to-watch-2 pull request #12
Opened 2023-04-04 10:51 UTC by vya58

2023-04-09 09:11 UTC, dionisvl requested changes

2023-04-09 09:11 UTC, dionisvl commented on app/Services/FilmService.php
> +    private function findOrCreateModelsAndGetIds(string $className, array $modelNames): array|\Exception
вот этот метод костыль знатный конечно
Давай лучше удалим его полностью и каждую модель обработаем в своём собственном Foreach просто внутри метода saveFilm, не надо заморачиваться тут.

2023-04-09 09:24 UTC, dionisvl commented on app/Services/FilmService.php
> +    private function findOrCreateModelsAndGetIds(string $className, array $modelNames): array|\Exception
еще упало 2 теста 

-  Tests\Feature\FilmRouteTest
- Tests\Unit\ImdbProxyRepositoryTest

2023-04-11 10:51 UTC, vya58 commented on app/Services/FilmService.php
> +    private function findOrCreateModelsAndGetIds(string $className, array $modelNames): array|\Exception
Костыль убрал, логику перенёс в saveFilm().
Исправил ошибки прохождения тестов.

2023-04-11 11:33 UTC, merged